default_platform(:android)

platform :android do
  desc "Deploy to Google Play Internal Testing Track"
  lane :deploy_internal do
    puts "Using package name: app.couldai.app"
    
    upload_to_play_store(
      package_name: 'app.couldai.app',
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_data: ENV["GOOGLE_PLAY_SERVICE_ACCOUNT_JSON"],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: 'completed'
    )
  end
end
